[Hero][Jed] Mobile to Tablet Screens
ezerssss/unihub-web pull request #2
Opened 2023-06-29 16:06 UTC by jedmamosto

Finished the mobile to tablet screen sizes. Desktop screens will figure out pa. 

Let me know for any formatting, tailwind errors, or file structure errors.

2023-06-29 16:10 UTC, jedmamosto commented
Added a fix for a missed space.

Also, here are the images:

**Mobile Screen:** 

![image](https://github.com/ezerssss/unihub-web/assets/124409966/781a0322-55a3-43fc-abd9-4ba1ed432c1e)

**Tablet Screen:**

![image](https://github.com/ezerssss/unihub-web/assets/124409966/a7e28f6c-390a-4d3b-8ee9-79dc1717d41f)

2023-06-29 16:15 UTC, jedmamosto commented
Also added the colors pala to our tailwind config, plus i put the images sa public folder

2023-06-30 04:16 UTC, ezerssss requested changes
also compress the images, we want to make the images load faster

2023-06-30 04:16 UTC, ezerssss commented on app/components/PrimaryButton.tsx
> +  children?: React.ReactNode;
`children?: JSX.Element | JSX.Element[]`

2023-06-30 04:16 UTC, ezerssss commented on app/components/PrimaryButton.tsx
> +export default PrimaryButton;
looks like unnecessary abstraction, its just a `button` na HTML component, we can just put this directly sa component.

just remove this and put the button directly sa component ur using it in

2023-06-30 04:18 UTC, ezerssss requested changes
doesnt look like the figma for desktop screens

Actual:
![image](https://github.com/ezerssss/unihub-web/assets/72904036/6c7814a8-843c-4b70-a2ff-3351c08a047f)

Figma: 
![image](https://github.com/ezerssss/unihub-web/assets/72904036/40f5848a-eeba-40da-9b54-b451eb4644dc)

2023-06-30 04:34 UTC, ezerssss commented on app/Hero.tsx
> +		<div className="flex flex-col items-center">
make this a `section` element

2023-07-01 05:47 UTC, ezerssss approved these changes
lgtm

2023-07-01 06:37 UTC, merged